FileVersion = 1

[Project]
Name = "snappy-beef"
DefaultNamespace = "snappy"

[Configs.Debug.Win64]
LibPaths = ["$(ProjectDir)\\libs\\windows\\x64\\snappy_d.lib"]

[Configs.Release.Win64]
LibPaths = ["$(ProjectDir)\\libs\\windows\\x64\\snappy.lib"]